const CDN='https://cdn.emulatorjs.org/stable/data/';
const keys={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',a:'z',b:'x',start:'Enter',select:'Backspace'};
const romInput=document.querySelector('#rom'), status=document.querySelector('#status'), placeholder=document.querySelector('#placeholder'), game=document.querySelector('#game');
let currentUrl=null,loaded=false;
function setStatus(message){status.textContent=message}
function stopEmulator(){if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}game.replaceChildren();loaded=false;placeholder.hidden=false}
function loadRom(file){if(!file)return;if(!/\.(gb|gbc|zip)$/i.test(file.name)){setStatus('Choose a .gb, .gbc, or supported .zip game file.');return}stopEmulator();currentUrl=URL.createObjectURL(file);placeholder.hidden=true;setStatus(`Loading ${file.name}…`);
window.EJS_player='#game';window.EJS_core=/\.gbc$/i.test(file.name)?'gbc':'gb';window.EJS_gameUrl=currentUrl;window.EJS_gameName=file.name.replace(/\.(gb|gbc|zip)$/i,'');window.EJS_gameID='pokemon-rng-local-rom';window.EJS_pathtodata=CDN;window.EJS_startOnLoaded=true;window.EJS_color='#9bbc0f';window.EJS_backgroundColor='#9bbc0f';window.EJS_onGameStart=()=>{loaded=true;setStatus(`${file.name} · progress and save states are stored by the emulator in this browser.`)};window.EJS_onSaveState=()=>setStatus('Save state saved in this browser.');
const loader=document.createElement('script');loader.src=CDN+'loader.js';loader.onload=()=>{};loader.onerror=()=>setStatus('Emulator failed to load. Check network access to cdn.emulatorjs.org and retry.');document.body.append(loader)}
romInput.addEventListener('change',()=>loadRom(romInput.files?.[0]));
const dz=document.querySelector('#dropzone');dz.addEventListener('dragover',e=>{e.preventDefault();dz.classList.add('dragging')});dz.addEventListener('dragleave',()=>dz.classList.remove('dragging'));dz.addEventListener('drop',e=>{e.preventDefault();dz.classList.remove('dragging');loadRom(e.dataTransfer?.files?.[0])});
document.querySelector('#reset').addEventListener('click',()=>{if(!romInput.files?.[0]){setStatus('Load a ROM first.');return}loadRom(romInput.files[0])});
function keyEvent(name,type){const key=keys[name];if(!key||!loaded)return;const evt=new KeyboardEvent(type,{key,code:key===' '?'Space':key,bubbles:true,cancelable:true});document.dispatchEvent(evt);window.dispatchEvent(new KeyboardEvent(type,{key,code:key,bubbles:true,cancelable:true}))}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Backspace','Tab'].includes(e.key)){e.preventDefault();if(['Backspace','Tab'].includes(e.key))keyEvent('select','keydown')}});
for(const button of document.querySelectorAll('[data-button]')){const name=button.dataset.button;button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);keyEvent(name,'keydown')});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>keyEvent(name,'keyup'))}
document.addEventListener('keydown',e=>{if(e.repeat)return;const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',z:'a',Z:'a',x:'b',X:'b',Enter:'start',Backspace:'select',Tab:'select',' ':'a',Shift:'b'};if(map[e.key]){e.preventDefault();keyEvent(map[e.key],'keydown')}});document.addEventListener('keyup',e=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',z:'a',Z:'a',x:'b',X:'b',Enter:'start',Backspace:'select',Tab:'select',' ':'a',Shift:'b'};if(map[e.key])keyEvent(map[e.key],'keyup')});
