// A self-contained, instant-play Kanto-style tile adventure.
const canvas=document.querySelector('#screen'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const T=16,W=40,H=36;const pal={grass:'#78b85c',light:'#a8d878',dark:'#438c50',path:'#d8c58b',path2:'#cdb77b',water:'#58b9d0',water2:'#b3e5d8',roof:'#d85848',roof2:'#a83e38',wall:'#f0e0b4',trim:'#814b46',tree:'#296747',tree2:'#397b4d',fence:'#e9d99b',ink:'#272b36',flower:'#f6dd65'};
const map=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>y>29?'p':(x<2||x>37||y<2||y>33?'t':'g')));
// central town paths and route north
for(let y=0;y<H;y++){for(let x=17;x<=22;x++)if(y>5)map[y][x]='p'}for(let x=4;x<36;x++)for(let y=16;y<=21;y++)map[y][x]='p';
function house(x,y,w=6,h=5,roof='r'){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)map[yy][xx]=(yy===y?'r':'b');map[y+h-1][x+Math.floor(w/2)]='d'}
house(7,8,7,6);house(26,8,7,6);house(17,23,7,6);
// flower patches, hedges, route grass, pond
for(let y=3;y<12;y++)for(let x=3;x<12;x++)if((x+y)%3===0&&map[y][x]==='g')map[y][x]='f';
for(let y=3;y<10;y++)for(let x=27;x<36;x++)if((x+y)%4===0&&map[y][x]==='g')map[y][x]='f';
for(let y=11;y<15;y++)for(let x=3;x<8;x++)map[y][x]='w';
for(let x=12;x<16;x++)map[14][x]='h';for(let x=24;x<28;x++)map[14][x]='h';
// route 1 tall grass lanes
for(let y=3;y<16;y++)for(let x=18;x<22;x++)if(y<11&&x!==20)map[y][x]='g';
for(let y=0;y<H;y++)for(let x=0;x<W;x++)if((x===0||x===W-1||y===0||y===H-1)&&y<29)map[y][x]='t';
const solid=new Set(['t','w','h','r','b']);let px=19,py=19,dir='down',moving=false,step=0,busy=false,balls=5,hp=20,maxHp=20,encounterCooldown=0;
function tile(x,y){return map[y]?.[x]??'t'}
function drawTile(code,x,y){let X=x*T,Y=y*T;ctx.fillStyle=pal.grass;ctx.fillRect(X,Y,T,T);if(code==='g'){ctx.fillStyle=pal.light;if((x*3+y*7)%4===0)ctx.fillRect(X+3,Y+5,2,2);ctx.fillStyle=pal.dark;if((x+y)%3===0)ctx.fillRect(X+11,Y+11,2,3)}else if(code==='p'){ctx.fillStyle=pal.path2;ctx.fillRect(X,Y+13,T,2);if((x+y)%2===0){ctx.fillStyle='#ead9a1';ctx.fillRect(X+4,Y+5,2,2)}}else if(code==='f'){ctx.fillStyle=pal.grass;ctx.fillRect(X,Y,T,T);for(let i=0;i<3;i++){ctx.fillStyle=i===1?'#f28b9d':pal.flower;ctx.fillRect(X+3+i*4,Y+4+(i%2)*4,3,3);ctx.fillStyle=pal.dark;ctx.fillRect(X+5+i*3,Y+8,1,5)}}else if(code==='w'){ctx.fillStyle=pal.water;ctx.fillRect(X,Y,T,T);ctx.fillStyle=pal.water2;ctx.fillRect(X+2,Y+4+(x%2)*4,7,1);ctx.fillRect(X+9,Y+12,5,1)}else if(code==='t'){ctx.fillStyle=pal.tree;ctx.fillRect(X+1,Y+2,14,13);ctx.fillStyle=pal.tree2;ctx.fillRect(X+4,Y,8,8);ctx.fillStyle='#1e543c';ctx.fillRect(X+7,Y+10,3,5)}else if(code==='h'){ctx.fillStyle=pal.fence;ctx.fillRect(X,Y+5,T,6);ctx.fillStyle='#b89b62';ctx.fillRect(X,Y+7,T,2);ctx.fillRect(X+3,Y+2,3,12);ctx.fillRect(X+11,Y+2,3,12)}else if(code==='r'||code==='b'||code==='d'){if(code==='r'){ctx.fillStyle=pal.roof2;ctx.fillRect(X,Y,T,T);ctx.fillStyle=pal.roof;ctx.fillRect(X+1,Y+2,14,8);ctx.fillStyle='#f17960';ctx.fillRect(X+4,Y+1,8,2)}else{ctx.fillStyle=pal.wall;ctx.fillRect(X+1,Y,T-2,T);ctx.fillStyle=pal.trim;ctx.fillRect(X+1,Y+1,T-2,2);ctx.fillRect(X+2,Y+8,4,5);ctx.fillRect(X+10,Y+8,4,5)}if(code==='d'){ctx.fillStyle='#72534a';ctx.fillRect(X+5,Y+4,6,12);ctx.fillStyle='#e9c677';ctx.fillRect(X+9,Y+10,1,1)}}}
function drawRed(cx,cy){let X=cx*T,Y=cy*T;ctx.fillStyle='#202632';ctx.fillRect(X+4,Y+5,8,9);ctx.fillStyle='#df4d3d';ctx.fillRect(X+3,Y+2,10,5);ctx.fillRect(X+2,Y+4,12,2);ctx.fillStyle='#f2d2a1';ctx.fillRect(X+5,Y+6,6,5);ctx.fillStyle='#202632';if(dir==='down'){ctx.fillRect(X+6,Y+8,1,1);ctx.fillRect(X+10,Y+8,1,1)}else ctx.fillRect(X+9,Y+7,1,1);ctx.fillStyle='#315da0';ctx.fillRect(X+4,Y+11,8,4);ctx.fillStyle='#f0eee0';ctx.fillRect(X+5,Y+12,6,1);ctx.fillStyle='#273044';let sway=moving&&Math.floor(step/5)%2;ctx.fillRect(X+4,Y+14,3,2+sway);ctx.fillRect(X+9,Y+14,3,2+(1-sway))}
function render(){ctx.fillStyle=pal.grass;ctx.fillRect(0,0,160,144);const ox=px-5,oy=py-4;for(let sy=0;sy<10;sy++)for(let sx=0;sx<11;sx++)drawTile(tile(ox+sx,oy+sy),sx-1,sy-1);drawRed(5,4);requestAnimationFrame(render)}
function say(text,done){document.querySelector('#message').textContent=text;const box=document.querySelector('#dialogue');box.hidden=false;busy=true;box.onclick=()=>{box.hidden=true;busy=false;done?.()}}
function startBattle(){if(busy||encounterCooldown)return;busy=true;const id=[16,19,21,25,39,41,43,46,52,54,58,63,69,74,77,83,92,98,100,104,109,116,118,129,133][Math.random()*25|0]+1;const names={16:'Pidgey',19:'Rattata',21:'Spearow',25:'Pikachu',39:'Jigglypuff',43:'Oddish',52:'Meowth',54:'Psyduck',58:'Growlithe',69:'Bellsprout',74:'Geodude',83:'Farfetchd',92:'Gastly',98:'Krabby',104:'Cubone',116:'Horsea',118:'Goldeen',129:'Magikarp',133:'Eevee'};let name=names[id]||'Pidgey',enemyHp=100;const panel=document.querySelector('#battle');panel.hidden=false;document.querySelector('#wild-name').textContent='WILD '+name.toUpperCase();document.querySelector('#wild-sprite').src=`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;document.querySelector('#enemy-level').textContent='Lv '+(2+Math.random()*4|0);document.querySelector('#balls').textContent='× '+balls;document.querySelector('#battle-message').textContent=`A wild ${name} appeared!`;
const close=(text)=>{document.querySelector('#battle-message').textContent=text;setTimeout(()=>{panel.hidden=true;busy=false;encounterCooldown=50},850)};
document.querySelector('#fight').onclick=()=>{enemyHp-=35+Math.random()*25;document.querySelector('#enemy-hp').style.width=Math.max(0,enemyHp)+'%';if(enemyHp<=0){close(`The wild ${name} fainted!`);return}hp=Math.max(1,hp-(2+Math.random()*5|0));document.querySelector('#player-hp').style.width=hp/maxHp*100+'%';document.querySelector('#hp-readout').textContent=`${hp} / ${maxHp}`;document.querySelector('#battle-message').textContent=`Your starter attacked! ${name} counterattacked.`};
document.querySelector('#ball').onclick=()=>{if(!balls){document.querySelector('#battle-message').textContent='No Poké Balls left!';return}balls--;document.querySelector('#balls').textContent='× '+balls;if(Math.random()<(1-enemyHp/130)*.85+.15){close(`Gotcha! ${name} was caught!`)}else document.querySelector('#battle-message').textContent=`Oh no! ${name} broke free!`};document.querySelector('#run').onclick=()=>close('Got away safely!');}
function move(d){if(busy)return;dir=d;const [dx,dy]=({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[d],nx=px+dx,ny=py+dy;moving=true;step++;if(!solid.has(tile(nx,ny))){px=nx;py=ny;const c=tile(px,py);if(c==='g'&&py<15&&Math.random()<.13)startBattle();if(py<5)document.querySelector('#location').textContent='ROUTE 1';else document.querySelector('#location').textContent='PALLET TOWN'}setTimeout(()=>moving=false,90)}
const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};let last=0;window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(e.key)||keyMap[e.key])e.preventDefault();if(e.repeat)return;if(keyMap[e.key])move(keyMap[e.key]);if(['z','Z','Enter',' '].includes(e.key)){if(busy&& !document.querySelector('#battle').hidden)return;if(px>=17&&px<=24&&py>=22&&py<=29)say('PROF. OAK: The world of Pokémon awaits! Step into the tall grass to meet Pokémon.',()=>{});else say('A quiet path through the Kanto countryside.',()=>{})}if(['x','X','Shift'].includes(e.key)){const box=document.querySelector('#dialogue');if(!box.hidden){box.hidden=true;busy=false}}});
render();
