// Overworld art is drawn exclusively from PNG assets in pret/pokered.
const canvas=document.querySelector('#screen'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const ROOT='https://raw.githubusercontent.com/pret/pokered/d2704a63c26f9ba046ade877445216b3de0519a4/gfx/';
const tiles=new Image(),red=new Image();tiles.src=ROOT+'tilesets/overworld.png';red.src=ROOT+'sprites/red.png';
const T=16,W=40,H=36;
const map=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>y>29?'p':(x<2||x>37||y<2||y>33?'t':'g')));
for(let y=0;y<H;y++)for(let x=17;x<=22;x++)if(y>5)map[y][x]='p';for(let x=4;x<36;x++)for(let y=16;y<=21;y++)map[y][x]='p';
function house(x,y,w=7,h=6){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)map[yy][xx]=yy===y?'r':'b';map[y+h-1][x+(w>>1)]='d'}house(7,8);house(26,8);house(17,23);
for(let y=3;y<12;y++)for(let x=3;x<12;x++)if((x+y)%3===0&&map[y][x]==='g')map[y][x]='f';for(let y=3;y<10;y++)for(let x=27;x<36;x++)if((x+y)%4===0&&map[y][x]==='g')map[y][x]='f';for(let y=11;y<15;y++)for(let x=3;x<8;x++)map[y][x]='w';for(let x=12;x<16;x++)map[14][x]='h';for(let x=24;x<28;x++)map[14][x]='h';
for(let y=3;y<16;y++)for(let x=18;x<22;x++)if(y<11&&x!==20)map[y][x]='g';for(let y=0;y<H;y++)for(let x=0;x<W;x++)if((x===0||x===W-1||y===0||y===H-1)&&y<29)map[y][x]='t';
// Source rectangles are 16x16 cells in the original 256x96 overworld atlas (zero-based column,row).
const src={g:[9,2],p:[7,1],f:[10,2],w:[3,1],t:[0,0],h:[12,2],r:[5,0],b:[6,1],d:[2,1]};
const solid=new Set(['t','w','h','r','b']);let px=19,py=19,dir=0,busy=false,balls=5,hp=20,maxHp=20,encounterCooldown=0,walking=0;
function tile(x,y){return map[y]?.[x]??'t'}
function drawTile(code,x,y){const [sx,sy]=src[code]||src.g;if(tiles.complete&&tiles.naturalWidth)ctx.drawImage(tiles,sx*T,sy*T,T,T,x*T,y*T,T,T)}
// Red's source PNG is a 16x112 sheet of 16px sprite frames. Direction selects a frame row.
const playerFrame={down:0,up:1,left:2,right:3};
function drawRed(x,y){if(!red.complete||!red.naturalWidth)return;const row=playerFrame[dir]??0;const frame=(walking?Math.floor(performance.now()/170)%2:0);const sourceRow=(row+frame)%7;ctx.drawImage(red,0,sourceRow*T,T,T,x*T,y*T,T,T)}
const activeKeys=new Set();
const directionByCode={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};
let lastStepAt=0;const STEP_MS=135;
function updateMovement(now){if(busy||now-lastStepAt<STEP_MS)return;let chosen=null;for(const code of [...activeKeys].reverse()){if(directionByCode[code]){chosen=directionByCode[code];break}}if(chosen){lastStepAt=now;move(chosen)}}
function render(now=performance.now()){updateMovement(now);ctx.clearRect(0,0,canvas.width,canvas.height);const ox=px-5,oy=py-4;for(let sy=0;sy<10;sy++)for(let sx=0;sx<11;sx++)drawTile(tile(ox+sx,oy+sy),sx-1,sy-1);drawRed(5,4);requestAnimationFrame(render)}
function say(text){document.querySelector('#message').textContent=text;const box=document.querySelector('#dialogue');box.hidden=false;busy=true;box.onclick=()=>{box.hidden=true;busy=false}}
function startBattle(){if(busy||encounterCooldown)return;busy=true;const ids=[16,19,21,25,39,43,52,54,58,69,74,83,92,98,104,116,118,129,133],id=ids[Math.random()*ids.length|0],names={16:'Pidgey',19:'Rattata',21:'Spearow',25:'Pikachu',39:'Jigglypuff',43:'Oddish',52:'Meowth',54:'Psyduck',58:'Growlithe',69:'Bellsprout',74:'Geodude',83:'Farfetchd',92:'Gastly',98:'Krabby',104:'Cubone',116:'Horsea',118:'Goldeen',129:'Magikarp',133:'Eevee'};const name=names[id],panel=document.querySelector('#battle');let enemyHp=100;panel.hidden=false;document.querySelector('#wild-name').textContent='WILD '+name.toUpperCase();document.querySelector('#wild-sprite').src=`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;document.querySelector('#enemy-level').textContent='Lv '+(2+Math.random()*4|0);document.querySelector('#balls').textContent='× '+balls;document.querySelector('#battle-message').textContent=`A wild ${name} appeared!`;const close=text=>{document.querySelector('#battle-message').textContent=text;setTimeout(()=>{panel.hidden=true;busy=false;encounterCooldown=50},850)};document.querySelector('#fight').onclick=()=>{enemyHp-=35+Math.random()*25;document.querySelector('#enemy-hp').style.width=Math.max(0,enemyHp)+'%';if(enemyHp<=0){close(`${name} fainted!`);return}hp=Math.max(1,hp-(2+Math.random()*5|0));document.querySelector('#player-hp').style.width=hp/maxHp*100+'%';document.querySelector('#hp-readout').textContent=`${hp} / ${maxHp}`;document.querySelector('#battle-message').textContent=`Your Pokémon attacked! ${name} counterattacked.`};document.querySelector('#ball').onclick=()=>{if(!balls){document.querySelector('#battle-message').textContent='No Poké Balls left!';return}balls--;document.querySelector('#balls').textContent='× '+balls;if(Math.random()<(1-enemyHp/130)*.85+.15)close(`Caught ${name}!`);else document.querySelector('#battle-message').textContent=`${name} broke free!`};document.querySelector('#run').onclick=()=>close('Got away safely!')}
function move(d){if(busy)return;dir=d;walking++;const [dx,dy]=({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[d],nx=px+dx,ny=py+dy;if(!solid.has(tile(nx,ny))){px=nx;py=ny;if(tile(px,py)==='g'&&py<15&&Math.random()<.13)startBattle();document.querySelector('#location').textContent=py<5?'ROUTE 1':'PALLET TOWN'}setTimeout(()=>walking=Math.max(0,walking-1),125)}
window.addEventListener('keydown',e=>{if(directionByCode[e.code]){e.preventDefault();activeKeys.add(e.code);return}if(['Space','Enter','KeyZ','KeyX','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();if(['KeyZ','Enter','Space'].includes(e.code)){if(busy&&!document.querySelector('#battle').hidden)return;if(px>=17&&px<=24&&py>=22&&py<=29)say('PROF. OAK: The world of Pokémon awaits! Step into the tall grass to meet Pokémon.');else say('A quiet path through the Kanto countryside.')}if(['KeyX','ShiftLeft','ShiftRight'].includes(e.code)){const box=document.querySelector('#dialogue');if(!box.hidden){box.hidden=true;busy=false}}});
window.addEventListener('keyup',e=>{activeKeys.delete(e.code)});
window.addEventListener('blur',()=>activeKeys.clear());
render();
